name: Simulation Tests

on: [push, pull_request]

jobs:
  simulation-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ipykernel  # ensures the python3 kernel is installed
          python -m ipykernel install --user --name python3 --display-name "Python 3"
          pip install -r tests/requirements.txt

      - name: Install PyTorch CPU-only
        run: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Run tests
        run: |
          pytest -p no:warnings --disable-warnings tests/