name: Simulation Test

on: [push, pull_request]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      notebook-matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: List all notebooks
        id: set-matrix
        run: |
          NOTEBOOKS=$(printf '%s\n' \
            documentation/playground_mr0/mr0_FID_seq.ipynb \
            documentation/playground_mr0/mr0_SE_CPMG_seq.ipynb \
            documentation/playground_mr0/mr0_STE_3pulses_5echoes_seq.ipynb \
            documentation/playground_mr0/mr0_FLASH_2D_seq.ipynb \
            documentation/playground_mr0/mr0_EPI_2D_seq.ipynb \
            documentation/playground_mr0/mr0_DWI_SE_EPI.ipynb \
            documentation/playground_mr0/mr0_diffusion_prep_STEAM_2D_seq.ipynb \
            documentation/playground_mr0/mr0_RARE_2D_seq.ipynb \
            documentation/playground_mr0/mr0_TSE_2D_multi_shot_seq.ipynb \
            documentation/playground_mr0/mr0_GRE_to_FLASH.ipynb \
            documentation/playground_mr0/mr0_bSSFP_2D_seq.ipynb \
            documentation/playground_mr0/mr0_DREAM_STE_seq.ipynb \
          | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$NOTEBOOKS" >> $GITHUB_OUTPUT

  test-notebooks:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook: ${{fromJSON(needs.generate-matrix.outputs.notebook-matrix)}}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Generate sequence file
        run: |
          mkdir tests/simulation_test/seq_files
          python tests/simulation_test/generate_seq_files.py ${{ matrix.notebook }}
      - name: Install dependencies
        run: |
          pip install pypulseq
          pip install torchkbnufft

      - name: Cloning main branch
        run: |
          git clone https://github.com/MRsources/MRzero-Core.git main_branch
          mkdir tests/simulation_test/ref_files

      - name: Installing main branch version
        run: |
          pip install -e ./main_branch

      - name: Generate reference files
        run: |
          python tests/simulation_test/generate_ref_files.py
      
      - name: Uninstall main branch version and install current version
        run: |
          pip uninstall -y MRzeroCore
          pip install -e .

      - name: Generate actual files
        run: |
          mkdir tests/simulation_test/actual_files
          python tests/simulation_test/generate_actual_files.py

      - name: Run Simulation Test
        run: |
          python tests/simulation_test/test_simulation.py